### ISSUE TITLE
Prevent Docker image rebuild on every run

### ISSUE THREAD

**Issue by arjunbazinga** [mirrajabi/aider-github-workflows#1]
Thanks for the workflow!

I've identified a potential optimization. Reviewing the workflow timing from a [run](https://github.com/arjunbazinga/arjunbazinga.github.io/actions/runs/9778556908/job/26995946716) , I see it currently takes 1 minute to build before spending 30 seconds on the actual edits.

We can(?) improve the overall time by prebuilding the image and reusing it in subsequent runs, rather than rebuilding the image every time we call the workflow

Thanks

**Comment by mirrajabi** [comment]
@arjunbazinga Good to see you're using it! and nice idea!
[I've published the built image to GitHub Container Registry](https://github.com/mirrajabi/aider-github-action/pkgs/container/aider-github-action). Based on my quick search results I'm hoping that is enough for GitHub workflows to find the publicly published image. Could be that you need to use `@main` as action version.

Could you re-trigger your workflow and let me know if this worked, please?

**Comment by arjunbazinga** [comment]
Hey just ran another flow, it still seems to [recompute the docker image](https://github.com/arjunbazinga/arjunbazinga.github.io/actions/runs/9843744404/job/27175629967) , takes more time now ~3 mins

**Comment by mirrajabi** [comment]
I went down the rabbit hole of Docker GitHub actions and now understand their design decision better.
In [an attempt to pull pre-built action from registry](https://github.com/mirrajabi/aider-github-workflows-test/actions/runs/10442627600/job/28916014829) I can see that its either possible to use a GitHub repository as an action in which case the GitHub action will be rebuilt everytime, or use a docker image directly. When pulling Docker image, you need to pass all the env vars and args directly.

While both solution could work, for now I choose to not use the docker image to keep the development/testing process simpler. Specifically for the case where a new commit is published but no docker image is released. If by any chance this library became more popular I will consider the use of a pre-built docker image.

Meanwhile, if you really want to use a pre-built image, you can create a fork of this repo and change[ the step "Apply changes with Aider" ](https://github.com/mirrajabi/aider-github-workflows/blob/c4336bdc16f9c8a2184b41e25dc3bb93a192d56a/.github/workflows/aider-issue-to-pr.yml#L157)like so:

```yaml
      - name: Apply changes with Aider
        uses: docker://ghcr.io/mirrajabi/aider-github-action:latest
        timeout-minutes: ${{ inputs.chat-timeout }}
        env:
          OPENAI_API_KEY: ${{ secrets.openai_api_key }}
          ANTHROPIC_API_KEY: ${{ secrets.anthropic_api_key }}
          COHERE_API_KEY: ${{ secrets.cohere_api_key }}
          DEEPSEEK_API_KEY: ${{ secrets.deepseek_api_key }}
          GEMINI_API_KEY: ${{ secrets.gemini_api_key }}
          GROQ_API_KEY: ${{ secrets.groq_api_key }}
          OPENROUTER_API_KEY: ${{ secrets.openrouter_api_key }}
          FEATURE_REF: 'main' # The branch to run Aider on.
          MODEL: 'gpt-4o'
          AIDER_ARGS: '--yes --message "This PR is auto-generated by Aider Workflow."'
```

I will close this issue for now.
