### ISSUE TITLE
Workflow failed with permission

### ISSUE THREAD

**Issue by tninja** [mirrajabi/aider-github-workflows#10]
I got this error
```
The workflow is not valid. .github/workflows/aider-on-issue-labeled.yml (Line: 7, Col: 3): Error calling workflow 'mirrajabi/aider-github-workflows/.github/workflows/aider-issue-to-pr.yml@main'. The nested job 'create-pull-request' is requesting 'contents: write, issues: read, pull-requests: write', but is only allowed 'contents: read, issues: none, pull-requests: none'.
```

Given aider-on-issue-labeled.yml like this:

```
name: Auto-generate PR using Aider
on:
  issues:
    types: [labeled]

jobs:
  generate:
    uses: mirrajabi/aider-github-workflows/.github/workflows/aider-issue-to-pr.yml@main
    # Check if the label is 'aider'
    if: github.event.label.name == 'aider'
    with:
      issue-number: ${{ github.event.issue.number }}
      base-branch: ${{ github.event.repository.default_branch }}
      # Exit if the action is taking longer than 10 minutes
      chat-timeout: 10
      api_key_env_name: OPENAI_API_KEY
      model: o3-mini-2025-01-31
    secrets: 
      api_key_env_value: ${{ secrets.OPENAI_API_KEY }}
```

Would you mind help take a look? @mirrajabi Thanks

**Comment by mirrajabi** [comment]
Hi, as the error message suggests, the workflow must have the necessary permissions.
You could add them directly to your `aider-on-issue-labeled.yml` file which may fix the issue:
```
name: Auto-generate PR using Aider
on:
... // as before

permissions:
  issues: read
  pull-requests: write
  contents: write

jobs:
...  // as before
```
